import { Product } from './types.ts';

export const PRODUCTS: Product[] = [
  {
    id: 'comoda-rustica-4-gavetas',
    name: 'Cômoda Rústica com 4 Gavetas',
    style: 'Rústico Colonial',
    description: 'Cômoda em madeira maciça com acabamento rústico, ideal para ambientes que buscam calor e tradição. Possui 4 gavetas amplas com puxadores clássicos.',
    priceTotal: 'R$ 3.588,00',
    priceInstallment: '12x de R$ 299,00',
    originalPriceTotal: 'R$ 5.988,00',
    originalPriceInstallment: '12x de R$ 499,00',
    measures: 'Sob consulta',
    fabric: 'Madeira Maciça',
    image: 'https://i.imgur.com/NOqg4pS.jpeg',
    link: '#'
  },
  {
    id: 'comoda-bombe-escrivaninha',
    name: 'Cômoda Bômbe Escrivaninha',
    style: 'Clássico Francês',
    description: 'Peça versátil que une a elegância da cômoda bômbe com a funcionalidade de uma escrivaninha. Design curvilíneo e acabamento refinado.',
    priceTotal: 'R$ 7.548,00',
    priceInstallment: '12x de R$ 629,00',
    originalPriceTotal: 'R$ 9.948,00',
    originalPriceInstallment: '12x de R$ 829,00',
    measures: 'Sob consulta',
    fabric: 'Madeira Nobre',
    image: 'https://i.imgur.com/Yt7mVZB.png',
    link: '#'
  },
  {
    id: 'livreiro-rustico-1',
    name: 'Livreiro Rústico',
    style: 'Rústico Elegance',
    description: 'Livreiro imponente em madeira rústica, perfeito para organizar sua biblioteca com estilo e robustez. Prateleiras reforçadas e design atemporal.',
    priceTotal: 'R$ 9.948,00',
    priceInstallment: '12x de R$ 829,00',
    originalPriceTotal: 'R$ 20.028,00',
    originalPriceInstallment: '12x de R$ 1.669,00',
    measures: 'Sob consulta',
    fabric: 'Madeira de Demolição',
    image: 'https://i.imgur.com/8GGia35.jpeg',
    link: '#'
  },
  {
    id: 'livreiro-rustico-2',
    name: 'Livreiro Rústico',
    style: 'Rústico Tradicional',
    description: 'Mais uma opção de livreiro rústico com acabamento diferenciado. Peça sólida que traz a beleza da madeira natural para seu escritório ou sala.',
    priceTotal: 'R$ 9.948,00',
    priceInstallment: '12x de R$ 829,00',
    originalPriceTotal: 'R$ 20.028,00',
    originalPriceInstallment: '12x de R$ 1.669,00',
    measures: 'Sob consulta',
    fabric: 'Madeira Maciça',
    image: 'https://i.imgur.com/taY7XEH.jpeg',
    link: '#'
  },
  {
    id: 'comoda-bombe-marchetada',
    name: 'Cômoda Bômbe Marchetada',
    style: 'Marchetaria Clássica',
    description: 'Trabalho primoroso de marchetaria em uma cômoda bômbe de lines clássicas. Uma verdadeira joia para decorar seu quarto ou hall de entrada.',
    priceTotal: 'R$ 2.988,00',
    priceInstallment: '12x de R$ 249,00',
    originalPriceTotal: 'R$ 4.500,00',
    originalPriceInstallment: '12x de R$ 375,00',
    measures: 'Sob consulta',
    fabric: 'Madeira com Marchetaria',
    image: 'https://i.imgur.com/eDUVmOK.png',
    link: '#'
  },
  {
    id: 'livreiro-rustico-marchetado',
    name: 'Livreiro Rústico Marchetado',
    style: 'Rústico com Detalhes',
    description: 'A união do rústico com a delicadeza da marchetaria. Um livreiro único que se destaca pela riqueza de detalhes e qualidade construtiva.',
    priceTotal: 'R$ 3.588,00',
    priceInstallment: '12x de R$ 299,00',
    originalPriceTotal: 'R$ 5.820,00',
    originalPriceInstallment: '12x de R$ 485,00',
    measures: 'Sob consulta',
    fabric: 'Madeira Marchetada',
    image: 'https://i.imgur.com/vmNtMPo.png',
    link: '#'
  },
  {
    id: 'recamier-classico-bege',
    name: 'Recamier Clássico Bege',
    style: 'Imperial Bege',
    description: 'Conforto e sofisticação em um recamier clássico com estofamento bege de alta qualidade. Ideal para pés de cama ou halls de entrada luxuosos.',
    priceTotal: 'R$ 7.188,00',
    priceInstallment: '12x de R$ 599,00',
    originalPriceTotal: 'R$ 9.588,00',
    originalPriceInstallment: '12x de R$ 799,00',
    measures: 'Sob consulta',
    fabric: 'Tecido Premium Bege',
    image: 'https://i.imgur.com/VIHMBFH.jpeg',
    link: '#'
  },
  {
    id: 'mesa-centro-classica',
    name: 'Mesa de Centro Clássica',
    style: 'Luís XV',
    description: 'Mesa de centro com pés entalhados e design clássico. O complemento perfeito para uma sala de estar elegante e acolhedora.',
    priceTotal: 'R$ 1.188,00',
    priceInstallment: '12x de R$ 99,00',
    originalPriceTotal: 'R$ 1.788,00',
    originalPriceInstallment: '12x de R$ 149,00',
    measures: 'Sob consulta',
    fabric: 'Madeira Entalhada',
    image: 'https://i.imgur.com/t8O6yWW.jpeg',
    link: '#'
  },
  {
    id: 'mesa-auxiliar-classica',
    name: 'Mesa Auxiliar Clássica',
    style: 'Clássico Versátil',
    description: 'Pequena mesa auxiliar com grandes detalhes. Prática e charmosa, pode ser usada como mesa lateral ou de apoio em diversos ambientes.',
    priceTotal: 'R$ 1.188,00',
    priceInstallment: '12x de R$ 99,00',
    originalPriceTotal: 'R$ 2.388,00',
    originalPriceInstallment: '12x de R$ 199,00',
    measures: 'Sob consulta',
    fabric: 'Madeira Nobre',
    image: 'https://i.imgur.com/D20asvP.jpeg',
    link: '#'
  },
  {
    id: 'diva-classico',
    name: 'Divã Clássico',
    style: 'Vitoriano',
    description: 'Divã luxuoso com design vitoriano, proporcionando um toque de realeza ao seu ambiente. Estofamento capitonê e curvas elegantes.',
    priceTotal: 'R$ 6.588,00',
    priceInstallment: '12x de R$ 549,00',
    originalPriceTotal: 'R$ 12.000,00',
    originalPriceInstallment: '12x de R$ 1.000,00',
    measures: 'Sob consulta',
    fabric: 'Veludo Premium',
    image: 'https://i.imgur.com/tJkVgnu.jpeg',
    link: '#'
  },
  {
    id: 'cadeira-classica-1',
    name: 'Cadeira Clássica',
    style: 'Jantar Imperial',
    description: 'Cadeira de jantar com design clássico e encosto trabalhado. Conforto e elegância para suas refeições e momentos especiais.',
    priceTotal: 'R$ 1.188,00',
    priceInstallment: '12x de R$ 99,00',
    originalPriceTotal: 'R$ 1.788,00',
    originalPriceInstallment: '12x de R$ 149,00',
    measures: '107x51x57cm',
    fabric: 'Madeira e Estofado',
    image: 'https://images.tcdn.com.br/img/img_prod/1200797/cadeira_de_jantar_classica_107x51x57cm_39237_2_c2add22d59430b5a14732bbc39cc8c6d.jpg',
    link: '#'
  },
  {
    id: 'recamier-classica-1',
    name: 'Recamier Clássica',
    style: 'Elegance Noir',
    description: 'Recamier com design clássico e acabamento impecável. Uma peça que une funcionalidade e beleza estética para seu quarto.',
    priceTotal: 'R$ 3.588,00',
    priceInstallment: '12x de R$ 299,00',
    originalPriceTotal: 'R$ 5.988,00',
    originalPriceInstallment: '12x de R$ 499,00',
    measures: 'Sob consulta',
    fabric: 'Tecido Nobre',
    image: 'https://i.imgur.com/C8232wb.jpeg',
    link: '#'
  },
  {
    id: 'recamier-classica-2',
    name: 'Recamier Clássica',
    style: 'Royal Comfort',
    description: 'Outra variação da nossa recamier clássica, com detalhes que encantam e proporcionam um descanso luxuoso.',
    priceTotal: 'R$ 3.588,00',
    priceInstallment: '12x de R$ 299,00',
    originalPriceTotal: 'R$ 5.988,00',
    originalPriceInstallment: '12x de R$ 499,00',
    measures: 'Sob consulta',
    fabric: 'Veludo Soft',
    image: 'https://i.imgur.com/x50wTVG.jpeg',
    link: '#'
  },
  {
    id: 'espelho-classico-ouro',
    name: 'Espelho Clássico Folheado a Ouro',
    style: 'Barroco Dourado',
    description: 'Espelho com moldura ricamente trabalhada e folheada a ouro. Uma peça de destaque que amplia e ilumina o ambiente com luxo.',
    priceTotal: 'R$ 468,00',
    priceInstallment: '12x de R$ 39,00',
    originalPriceTotal: 'R$ 708,00',
    originalPriceInstallment: '12x de R$ 59,00',
    measures: 'Sob consulta',
    fabric: 'Moldura Folheada a Ouro',
    image: 'https://i.imgur.com/YB7GO8E.jpeg',
    link: '#'
  },
  {
    id: 'poltrona-classica-1',
    name: 'Poltrona Clássica',
    style: 'Bergère Tradicional',
    description: 'Poltrona clássica com encosto alto e braços envolventes. O máximo em conforto e estilo para seu momento de relaxamento.',
    priceTotal: 'R$ 2.988,00',
    priceInstallment: '12x de R$ 249,00',
    originalPriceTotal: 'R$ 4.188,00',
    originalPriceInstallment: '12x de R$ 349,00',
    measures: 'Sob consulta',
    fabric: 'Veludo Premium',
    image: 'https://i.imgur.com/GbRkMcI.jpeg',
    link: '#'
  },
  {
    id: 'sofa-3-lugares-classico-1',
    name: 'Sofá de 3 Lugares Clássico',
    style: 'Chesterfield Style',
    description: 'Sofá amplo de 3 lugares com design clássico e estofamento capitonê. Imponência e conforto para receber seus convidados.',
    priceTotal: 'R$ 4.788,00',
    priceInstallment: '12x de R$ 399,00',
    originalPriceTotal: 'R$ 7.188,00',
    originalPriceInstallment: '12x de R$ 599,00',
    measures: 'Sob consulta',
    fabric: 'Tecido de Alta Qualidade',
    image: 'https://i.imgur.com/g3v10fN.jpeg',
    link: '#'
  },
  {
    id: 'sofa-3-lugares-classico-2',
    name: 'Sofá de 3 Lugares Clássico',
    style: 'Majestic Sofa',
    description: 'Sofá de alto padrão com detalhes entalhados e conforto excepcional. Uma peça central para uma sala de estar de prestígio.',
    priceTotal: 'R$ 7.188,00',
    priceInstallment: '12x de R$ 599,00',
    originalPriceTotal: 'R$ 11.988,00',
    originalPriceInstallment: '12x de R$ 999,00',
    measures: 'Sob consulta',
    fabric: 'Veludo de Luxo',
    image: 'https://i.imgur.com/i2ZzK31.jpeg',
    link: '#'
  },
  {
    id: 'comoda-classica-1',
    name: 'Cômoda Clássica',
    style: 'Vintage Elegance',
    description: 'Cômoda com design vintage e acabamento clássico. Gavetas funcionais e estética refinada para organizar seu espaço com charme.',
    priceTotal: 'R$ 3.588,00',
    priceInstallment: '12x de R$ 299,00',
    originalPriceTotal: 'R$ 4.788,00',
    originalPriceInstallment: '12x de R$ 399,00',
    measures: 'Sob consulta',
    fabric: 'Madeira Nobre',
    image: 'https://i.imgur.com/SoyPHv6.png',
    link: '#'
  },
  {
    id: 'espelho-veneziano',
    name: 'Espelho Decorativo Veneziano',
    style: 'Veneziano Autêntico',
    description: 'Espelho com design veneziano e detalhes sofisticados. Uma peça de arte que traz a tradição de Veneza para sua decoração.',
    priceTotal: 'R$ 1.068,00',
    priceInstallment: '12x de R$ 89,00',
    originalPriceTotal: 'R$ 1.548,00',
    originalPriceInstallment: '12x de R$ 129,00',
    measures: '100x82cm',
    fabric: 'Cristal e Detalhes Venezianos',
    image: 'https://images.tcdn.com.br/img/img_prod/1200797/espelho_decorativo_veneziano_100x82cm_espelho_de_parede_de_design_classico_detalhes_sofisticados_33886_2_0b52f8638f48f7076b31cfd234e3802c.jpg',
    link: '#'
  },
  {
    id: 'armario-classico',
    name: 'Armário Clássico',
    style: 'Garderobe Royal',
    description: 'Armário imponente com portas trabalhadas e amplo espaço interno. Organização e luxo em uma única peça de mobiliário.',
    priceTotal: 'R$ 4.188,00',
    priceInstallment: '12x de R$ 349,00',
    originalPriceTotal: 'R$ 5.988,00',
    originalPriceInstallment: '12x de R$ 499,00',
    measures: 'Sob consulta',
    fabric: 'Madeira Maciça',
    image: 'https://i.imgur.com/HSL7g0T.jpeg',
    link: '#'
  },
  {
    id: 'cadeira-classica-2',
    name: 'Cadeira Clássica',
    style: 'Medalhão',
    description: 'Cadeira estilo medalhão com encosto oval e estofamento confortável. Um clássico que nunca sai de moda para sua sala de jantar.',
    priceTotal: 'R$ 1.188,00',
    priceInstallment: '12x de R$ 99,00',
    originalPriceTotal: 'R$ 2.388,00',
    originalPriceInstallment: '12x de R$ 199,00',
    measures: 'Sob consulta',
    fabric: 'Madeira e Veludo',
    image: 'https://i.imgur.com/NPI3pWH.jpeg',
    link: '#'
  },
  {
    id: 'cadeira-classica-3',
    name: 'Cadeira Clássica',
    style: 'Luis Felipe',
    description: 'Cadeira com lines retas e elegantes, característica do estilo Luis Felipe. Versátil e sofisticada para diversos ambientes.',
    priceTotal: 'R$ 1.188,00',
    priceInstallment: '12x de R$ 99,00',
    originalPriceTotal: 'R$ 2.388,00',
    originalPriceInstallment: '12x de R$ 199,00',
    measures: 'Sob consulta',
    fabric: 'Madeira Nobre',
    image: 'https://i.imgur.com/7OrSDwR.jpeg',
    link: '#'
  },
  {
    id: 'espelho-classico-2',
    name: 'Espelho Clássico',
    style: 'Moldura Entalhada',
    description: 'Espelho decorativo com moldura entalhada à mão. Traz profundidade e um toque de antiguidade charmosa para sua parede.',
    priceTotal: 'R$ 2.988,00',
    priceInstallment: '12x de R$ 249,00',
    originalPriceTotal: 'R$ 4.788,00',
    originalPriceInstallment: '12x de R$ 399,00',
    measures: 'Sob consulta',
    fabric: 'Moldura em Madeira',
    image: 'https://images.tcdn.com.br/img/img_prod/1200797/espelho_decorativo_clssico_4_20260312115719_5670d7530527.jpg',
    link: '#'
  },
  {
    id: 'aparador-classico',
    name: 'Aparador Clássico',
    style: 'Console de Luxo',
    description: 'Aparador elegante para hall de entrada ou sala de jantar. Design esguio com detalhes que valorizam qualquer espaço.',
    priceTotal: 'R$ 2.388,00',
    priceInstallment: '12x de R$ 199,00',
    originalPriceTotal: 'R$ 4.188,00',
    originalPriceInstallment: '12x de R$ 349,00',
    measures: 'Sob consulta',
    fabric: 'Madeira e Verniz',
    image: 'https://i.imgur.com/3tUc7J8.jpeg',
    link: '#'
  }
];
